# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calmatrix.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cal_Matrix(object):
    def setupUi(self, Cal_Matrix):
        Cal_Matrix.setObjectName("Cal_Matrix")
        Cal_Matrix.resize(551, 281)
        self.splitter = QtWidgets.QSplitter(Cal_Matrix)
        self.splitter.setGeometry(QtCore.QRect(40, 50, 471, 192))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnInitData = QtWidgets.QPushButton(self.widget)
        self.btnInitData.setObjectName("btnInitData")
        self.verticalLayout.addWidget(self.btnInitData)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSetRows = QtWidgets.QPushButton(self.widget)
        self.btnSetRows.setObjectName("btnSetRows")
        self.horizontalLayout.addWidget(self.btnSetRows)
        self.spinBox = QtWidgets.QSpinBox(self.widget)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btnAppendRow = QtWidgets.QPushButton(self.widget)
        self.btnAppendRow.setObjectName("btnAppendRow")
        self.verticalLayout.addWidget(self.btnAppendRow)
        self.btnDelRow = QtWidgets.QPushButton(self.widget)
        self.btnDelRow.setObjectName("btnDelRow")
        self.verticalLayout.addWidget(self.btnDelRow)
        self.btnRes = QtWidgets.QPushButton(self.widget)
        self.btnRes.setObjectName("btnRes")
        self.verticalLayout.addWidget(self.btnRes)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnAutoHeight = QtWidgets.QPushButton(self.widget)
        self.btnAutoHeight.setObjectName("btnAutoHeight")
        self.verticalLayout_2.addWidget(self.btnAutoHeight)
        self.btnAutoWidth = QtWidgets.QPushButton(self.widget)
        self.btnAutoWidth.setObjectName("btnAutoWidth")
        self.verticalLayout_2.addWidget(self.btnAutoWidth)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.tableWidget = QtWidgets.QTableWidget(self.splitter)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)

        self.retranslateUi(Cal_Matrix)
        QtCore.QMetaObject.connectSlotsByName(Cal_Matrix)

    def retranslateUi(self, Cal_Matrix):
        _translate = QtCore.QCoreApplication.translate
        Cal_Matrix.setWindowTitle(_translate("Cal_Matrix", "可压性矩阵计算"))
        self.btnInitData.setText(_translate("Cal_Matrix", "恢复默认参数"))
        self.btnSetRows.setText(_translate("Cal_Matrix", "设置参数个数"))
        self.btnAppendRow.setText(_translate("Cal_Matrix", "添加参数"))
        self.btnDelRow.setText(_translate("Cal_Matrix", "删除参数"))
        self.btnRes.setText(_translate("Cal_Matrix", "计算权重"))
        self.btnAutoHeight.setText(_translate("Cal_Matrix", "自动高度"))
        self.btnAutoWidth.setText(_translate("Cal_Matrix", "自动宽度"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Cal_Matrix", "参数名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Cal_Matrix", "等级"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Cal_Matrix", "权重"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Cal_Matrix = QtWidgets.QWidget()
    ui = Ui_Cal_Matrix()
    ui.setupUi(Cal_Matrix)
    Cal_Matrix.show()
    sys.exit(app.exec_())
